### ISSUE TITLE
Get combined @ and #

### ISSUE THREAD

**Issue by kaleidografik** [kasperlegarth/instastory.js#14]
Hi there, is it possible in the 'get' option to conbine @ and #? For example, if I wanted to retrieve posts from @myuser, but only those tagged with @myhashtag?

Thanks!

**Comment by kasperlegarth** [comment]
Hi @kaleidografik. Sadly the URL endpoint does not support this, The way you would do is to start by getting all the posts from the user, then store the results in an array or object and then filter it with the hashtag. It is not something that can be done with the plugin. 

However, I think the idea of having an option for the plugin to only return data is a good idea. I may pursue this in the future.

If you would like to try and make the desired functionality your self, I will be happy to help :) Please let me know if you have further questions.
