### ISSUE TITLE
Keen we read the comments of the posts

### ISSUE THREAD

**Issue by vivekg-git** [kasperlegarth/instastory.js#15]
@kasperlegarth this is great. Can we read the comments of each post. It will be really good to have this option.

**Comment by kasperlegarth** [comment]
Hi, @vivekg-git thank you :-) 
Sadly the API does not return the comments. Only the number of comments in total. That number can be used with the templating system. For more information see: [https://github.com/kasperlegarth/instastory.js#templating](https://github.com/kasperlegarth/instastory.js#templating )
