### ISSUE TITLE
Can't get templating to work

### ISSUE THREAD

**Issue by vbroskas** [kasperlegarth/instastory.js#16]
The plugin works fine if I use:
```
$("#container").instastory({
    get: "@nm_asian_family_center",
    limit: 9
});
```
or even using an object without a template, such as:
```
let options = {
 get: "@nm_asian_family_center",
 limit: 9,
};

$("#insta-container-footer").instastory(options);
```

However, as soon as I add in a template and inspect the result in devtools I see elements with:
`<img src=(unknown) alt="">`

Here is my example with a template:
```
let options = {
   get: "@nm_asian_family_center",
   limit: 9,
   template: '<img src="{{image}}" alt="">',
};
$("#insta-container-footer").instastory(options);
```
Any idea what I'm doing wrong? Thanks for any help!

**edit**
noticed that other tags in the template such as `{{link}}` are returning blank info as well.

**Final Edit**
I'm going to close this, I'm really dumb, and forgot that django will try and render the {{}} used in your plugin. Even more sad is that it took me having to go over all your code until the `allReplace` function till I realized my mistake. Thanks for the great plugin, everything is working fine now!

**Comment by kasperlegarth** [comment]
Hi @vbroskas, you’re welcome. I’m glad that you figured it out.
