### ISSUE TITLE
Stopped working with undefined error

### ISSUE THREAD

**Issue by elemis** [kasperlegarth/instastory.js#17]
The feeds suddenly stopped working returning the error:
`TypeError: undefined is not an object (evaluating 'e.graphql[o.type]')`
![Screen Shot 2020-06-05 at 16 00 55](https://user-images.githubusercontent.com/608547/83879520-6c9d0300-a746-11ea-9d46-0148947f0dc4.png)
Seeing the same error on the official demo too and the user based feed doesn't work there as well. What might be the reason?

**Comment by kasperlegarth** [comment]
Hi @elemis 
Do you still have this problem? - I can't seem to recreate the problem? It works fine on the demo?

**Comment by elemis** [comment]
Hi @kasperlegarth it somehow started to work properly after 5 days. Maybe it was an IP block? Anyway thanks :)

**Comment by fruecker** [comment]
Hi, i think i got a similar problem. Do u know what might have happened?
```
Uncaught TypeError: data.graphql is undefined
    success https://cdn.jsdelivr.net/gh/kasperlegarth/instastory.js/instastory.js:152
    jQuery 6
        c
        fireWith
        l
        o
        send
        ajax
    instastory https://cdn.jsdelivr.net/gh/kasperlegarth/instastory.js/instastory.js:149
    <anonymous> http://127.0.0.1:5000/:10
```

My code:
```
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/gh/kasperlegarth/instastory.js/instastory.js"></script>

<h2>#memeventskalender</h2>
<div style="width: 100%; height: 100%;"class="container"></div>

<script type="application/javascript">
$(function() {
  console.log("Running");
  $(".container").instastory({
    get: "#memeventskalender",
    limit: 6
  });
});
</script>
```

**Comment by kasperlegarth** [comment]
Hi @fruecker 
It sounds like you are the victim of Instagram security settings on the URL. I have tried to explain it here: #21

The best way to test this is to access your project from another IP. The new device should have no problem. Let me know if that helps.

**Comment by fruecker** [comment]
Thanks! It helped. 
Really odd one, maybe u can add a error message that's suggesting the user to change ip. :) 
By the way, do u have any ideas why vpn didnt handle that problem? Because I tried that and it didnt fix it. Ended up using mobil-connection by my smartphone.

**But great job with your contribution! Works like a charm. Thank you very much.**
