### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hashtag' of undefined 

### ISSUE THREAD

**Issue by zebra0303** [kasperlegarth/instastory.js#22]
Hi,

Thanks for your library for 'instagram'.

Today I tried to get hash tag images from your library but the error occurred.

```
Uncaught TypeError: Cannot read property 'hashtag' of undefined
    at Object.<anonymous> (instastory.js:159)
    at u (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at k (jquery.min.js:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js:2)
```

Could you check upper issue?

-Larry

**Comment by kasperlegarth** [comment]
Hi Larry,
Can you share some code? What do you code, that triggers this error, looks like?

Is this happening to you after you have been using it for a while in a development environment? Or did it happen the first time you tried to use it?

**Comment by zebra0303** [comment]
For the first time I could get the photos well. but after some time I couldn't.

On your site also I can see the same error.
https://ibb.co/KGsbLyR

It seems instastory.js request the url 'https://www.instagram.com/explore/tags/sea/?__a=1' 
But the reulst is not JSON format just plain html page tag'
https://codeshare.io/aYoLLN

**Comment by kasperlegarth** [comment]
Hello again,
It sounds like you are the victim of Instagram security settings on the URL. I have tried to explain it here: #21
