### ISSUE TITLE
Search by username stopped working

### ISSUE THREAD

**Issue by miroslav-frost** [kasperlegarth/instastory.js#26]
Search by username stopped working today. "Uncaught TypeError: Cannot read property 'user' of undefined".

Search by hashtag still working

**Comment by kasperlegarth** [comment]
Hi @miroslav-frost 
I think you having issues with the limitations on the API. I have tried to explain it here: #21 It has to do with a large number of requests in a short amount of time. Which is typical for a developing process. I have just tried usernames on the demo (https://kasperlegarth.github.io/instastory.js/) and it works as it should.

Be aware that it is your IP that is getting limited, so try a VPN just to confirm that it works. This behavior should not happen to the end-user.

Hope that is making sense.

Please let me know if there is anything else I can help you with.
