### ISSUE TITLE
Callback functions

### ISSUE THREAD

**Issue by elemis** [kasperlegarth/instastory.js#9]
Just wondering if you're planning to add before / after callback functions?

**Comment by kasperlegarth** [comment]
Hi @elemis, i would differently like to add these, but i don't expect to have the time for this the next couple of months.

**Comment by elemis** [comment]
Hi @kasperlegarth, is there any other way of achieving this that you can suggest to use for the time being? I need to insert Instagram images in a carousel but the carousel script fails to work without after callback.

**Comment by kasperlegarth** [comment]
Thanks for the help with this :-)
